_core:
  default_config_hash: lhknqI_UWOrAbQH9SLBSF7MVG-hc49r4GShA8pFG4gY
scope_provider: ''
token_cron_batch_size: 10
public_key: ../keys/public.key
private_key: ../keys/private.key
access_token_expiration: 300
authorization_code_expiration: 300
refresh_token_expiration: 1209600
remember_clients: true
use_implicit: false
